export const SEARCH_USERS = 'SEARCH_USERS';
export const SEARCH_LOADING = 'SEARCH_LOADING';
export const STORE_SEARCH_RESULTS = 'STORE_SEARCH_RESULTS';
export const GET_GITHUB_REPOS = 'GET_GITHUB_REPOS';
export const STORE_GITHUB_REPOS = 'STORE_GITHUB_REPOS';
export const CREATE_PROJECT = "CREATE_PROJECT";